version: '3'

services:

  yolo-v4-train:

    build:
      context: ..
      dockerfile: "docker/Dockerfile"
      args:
        - CUDA_VER=${CUDA_VER}
        - UBUNTU_VER=${UBUNTU_VER} 

    image: pytorch-yolo-v4-train-img
    container_name: pytorch-yolo-v4-train
    environment:
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ "gpu" ]
              
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
              
    volumes:
      - ${REPO_DIR}:/repo
      - ${DATA_DIR}:/data

    network_mode: "host"

# sudo docker compose up --build
# sudo docker compose run -i --entrypoint bash --build yolo-v4-train
# HOST_UID="$(id -u)" HOST_GID="$(id -g)" docker compose up --build

